name: Deploy Lambda Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Auth/**'
      - 'newTest/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install zip tool
        uses: montudor/action-zip@v1

      # ------------------- Deploy src Lambda -------------------
      - name: Zip src lambda
        run: |
          cd src
          zip -r ../src_code.zip .
          cd ..

      - name: Deploy myTestFunction (src)
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: >
            lambda update-function-code
            --function-name arn:aws:lambda:ap-south-1:124030975021:function:myTestFunction
            --zip-file fileb://src_code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"

      # ------------------- Deploy Auth Lambda -------------------
      - name: Zip Auth lambda
        run: |
          cd Auth
          zip -r ../auth_code.zip .
          cd ..

      - name: Deploy DemoAuthorizer (Auth)
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: >
            lambda update-function-code
            --function-name arn:aws:lambda:ap-south-1:124030975021:function:DemoAuthorizer
            --zip-file fileb://auth_code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"

        # ------------------- Deploy new Test Lambda -------------------
      - name: Zip newTest lambda
        run: |
          cd newTest
          zip -r ../newtest_code.zip .
          cd ..

      - name: Deploy newTest2 (newTest)
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: >
            lambda update-function-code
            --function-name arn:aws:lambda:ap-south-1:124030975021:function:newTest2
            --zip-file fileb://newtest_code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
